using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using UnityEngine.UI;

public class AudioManager : MonoBehaviour
{

    public GameObject suelo;
    public GameObject coche;
    public TextMeshProUGUI collisionCounterText;
    //public Panel colocar;
    private int contadorColisiones = 0;
    // Start is called before the first frame update
    void Start()
    {
        if(collisionCounterText!=null){
            collisionCounterText.text = "Colisiones: " + contadorColisiones;
        }
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        
    }


    void OnCollisionEnter(Collision collision)
    {
        // Comprueba si el coche est√° colisionando con algo que no sea el suelo
        if (collision.gameObject != suelo)
        {
            // Incrementa el contador de colisiones
            contadorColisiones++;

            // Actualiza el texto de la UI para mostrar el nuevo contador
            //uiText.text = "Colisiones: " + contadorColisiones;
            collisionCounterText.text = "Colisiones: " + contadorColisiones;

            Debug.Log("Colisiones: " + contadorColisiones);
        }
    }
}
